### ISSUE TITLE
WeDo 1.0 - "Signed out" message in editor, failure to save project

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchx#102]
Chrome 55, Mac OS El Capitan, Staging (Online Editor)

- I plugged in the WeDo 1.0
- Added the extension
- The circle turned green
- Then I dragged a block to the scripting area
- I got the sign out message and project save failure in console
- The distance sensor block does work as expected though

<img width="1277" alt="screen shot 2016-12-19 at 12 57 29 pm" src="https://cloud.githubusercontent.com/assets/1320456/21323534/ec6cc204-c5eb-11e6-9a5e-b0a07d942daf.png">

<img width="419" alt="screen shot 2016-12-19 at 12 59 03 pm" src="https://cloud.githubusercontent.com/assets/1320456/21323538/f36837e6-c5eb-11e6-8895-b6f864d0b283.png">

**Comment by savaka2** [comment]
That has to do with official extensions and seems to be unrelated to ScratchX. You might want to post it in Scratch's [Bugs and Glitches](https://scratch.mit.edu/discuss/3/) forum.

**Comment by jwzimmer** [comment]
Thanks @savaka2, I am moving this to scratch-flash-online.
