### ISSUE TITLE
Chrome + MacOS Sierra issues?

### ISSUE THREAD

**Issue by kaschm** [LLK/scratchx#105]
Currently ScratchX in Chrome is not working on macOS Sierra. It looks like about 2 weeks ago Chrome made an update and since then it has not been working.

**Comment by cwillisf** [comment]
I can't seem to repro this: ScratchX is working for me with Chrome on Sierra. @kaschm any chance you can get more info about the specific problem the reporter was seeing?

I tested with:
macOS Sierra 10.12.2
Chrome 55.0.2883.95 (64-bit)

**Comment by kaschm** [comment]
The reporter is no longer seeing the issue. Closing this!
