### ISSUE TITLE
Firefox, MacOS, the serial 

### ISSUE THREAD

**Issue by githubhero** [LLK/scratchx#106]
Hi, I was trying to connect a little piece of very common hardware to ScratchX using the serial. I got the "green light" when they connected but they can't communicate since for some reason `set_receive_handler` never gets called.

Hw/Sw info:
MacOS Sierra 10.12.2
Firefox 50.1.0

**Comment by cwillisf** [comment]
`set_receive_handler` is something you'll need to call yourself. The pattern is:
1. Your extension's `deviceOpened` function will be called with the new device.
2. In `deviceOpened` you should verify that the device in question is actually a device you're interested in. For example, with the PicoBoard extension we send a request for the PicoBoard to report its sensor values, and if we don't receive sensor values in a reasonable amount of time then we assume that the device must not be a PicoBoard.
3. Now that you know it's your device, call `set_receive_handler` with your extension's desired handler.

I'd recommend checking out the PicoBoard extension as an example, starting at `deviceOpened`: https://github.com/LLK/scratchx/blob/gh-pages/scratch_extensions/picoExtension.js

**Comment by githubhero** [comment]
Hi @cwillisf, first of all thanks for your kind reply.

Sorry for expressing the concept so bad: I wanted to say that the callback you pass as an argument in set_receive_handler is never executed.

I knew the Picoboard code: mine si very similar but it is not working for me (moreover: I only have one connection with one device).

What happens: 

- the device is connected and it regularly prints to the serial (I see it using CoolTerm): I click a physical button and I see it printing to the console;

- the device apparently gets connected to ScratchX (green color):  
`Object { id: "/dev/tty.usbmodem1432", open: SerialDevice/this.open(), close: SerialDevice/this.close(), send: SerialDevice/this.send(), set_receive_handler: SerialDevice/this.set_receive_handler() } `

- ScratchX is not printing/sending/writing to the serial;

- ScratchX is not receiving anything (I'm supposing I can catch something coming from the serial via set_receive_handler);

**Comment by jerryyip** [comment]
I have the same problem here. What should I do now? @thisandagain @cwillisf
