### ISSUE TITLE
Cannot load additional extension from modal dialog within editor

### ISSUE THREAD

**Issue by sayamindu** [LLK/scratchx#11]
* Open scratchx.org
* Click on the Text to Speech extension link
* Click on the "Load experimental extension" button once the editor is visible

The modal that pops up does not go away when I select "mesh" extension from the dialog:

![image](https://cloud.githubusercontent.com/assets/163931/7552765/129bbba2-f699-11e4-97ec-8eed2796dc8f.png)

**Comment by 2jour** [comment]
prig-high because there doesn't seem to be a way to go back to the editor.
