### ISSUE TITLE
FireFox updates...Scratchx extension plugins no longer works

### ISSUE THREAD

**Issue by joellehippo** [LLK/scratchx#115]
Hi, my firefox browser was automatically updated to v52.0 and when I try to load extensions in Scratchx, it keeps providing an error message that says "missing plugin". Any ideas to fix this error? Any help is greatly appreciated!

Hardware: Arduino Uno

**Comment by khanning** [comment]
I am able to get ScratchX to load on Firefox 52 on Mac OSX. 

Make sure you have the latest version of [flash player](https://get.adobe.com/flashplayer/) installed and that you have allowed "Adobe flash" to run on ScratchX.

<img width="647" alt="image" src="https://cloud.githubusercontent.com/assets/1169507/23994505/931bc0b4-0a1b-11e7-9ded-3fd653e33d9e.png">
