### ISSUE TITLE
Firefox 52 dropped support for NPAPI plugins

### ISSUE THREAD

**Issue by khanning** [LLK/scratchx#116]
Firefox version 52 has [removed support for NPAPI plugins](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Why-do-Java-Silverlight-Adobe-Acrobat-and-other-plugins-no/ta-p/31069). This means that the Scratch Device Plugin will no longer work in Firefox. [Firefox ESR](https://www.mozilla.org/firefox/organizations/all/) will continue to support NPAPI plugins until early 2018.

Since serial device connections are not working properly with the Chrome version of the plugin (#55), Firefox ESR is currently the only option for people using the Arduino, iRobot, EV3, or any other serial device extensions.

**Comment by lmayorgav** [comment]
i still can´t install the extension even with firefox ESR

**Comment by jim-stoll** [comment]
FWIW, I the plugin is working under Safari (v11) on Mac (Sierra), and IE (v11) on Windows 10.

**Comment by cotestatnt** [comment]
Waiting for a definitive fix, i solved with a Firefox portable version 51.0 32bit where i copied the plugin dll in .\.App\DefaultData\plugins. 
Not elegant, but it works!

**Comment by towerofnix** [comment]
Note there will almost certainly never be a fix to this. The ST plans to deprecate ScratchX once Scratch 3.0 is released, as 3.0 has its own built-in extension system (which will eventually include extensions created by third-party developers). Scratch 3.0 comes with a tool called Scratch Link, which is designed to replace the Scratch Device Manager and is more reliable on recent systems (AFAIK there's no problem with it on Firefox, although I haven't tested it myself).

**Comment by JanusChoi** [comment]
Try a few work-around and I've given up this solution and turn to use s4a refer to s4a.cat.
