### ISSUE TITLE
How to add more Blocks  for Arduino 101 on ScratchX ?

### ISSUE THREAD

**Issue by JimmyLai0908** [LLK/scratchx#117]
Hello ScatchX Team ,

This is Jimmy from Taiwan . I am very interesting in Scratch . And it is useful and fun for Arduino 101 board by using this web :
http://scratchx.org/?url=https://llk.github.io/arduino-101/arduino101_serial_extension.js

But now I want to add more Blocks to do more things for Arduino 101 by Scratchx . 
Could you tell me how to get the javascript code (arduino101_serial_extension.js ) on github ?
(Because I wanna use it as base to add more extension for arduino 101.)
Thank you for your assiatance !

Sincerely!

**Comment by savaka2** [comment]
I think the repo is private

**Comment by JimmyLai0908** [comment]
@savaka2  : Hello , thank your reply !
