### ISSUE TITLE
Projects persist unexpectedly

### ISSUE THREAD

**Issue by sayamindu** [LLK/scratchx#12]
* Open scratchx.org
* Click on the Text to Speech extension link
* Click on the ScratchX logo on the editor when it shows up
* Click on Mesh when homepage shows up

Items from the previous project are still visible on the editor. It seems it should have a new empty project instead.

**Comment by rschamp** [comment]
Fixed by c07409ab54dd6d0eb9b97b9fec79bf061eaac1d3 and e2f1fc25f2bc5575955394509c71c0b629996dab
