### ISSUE TITLE
ScratchX: Saving Project to Local Hard Drive Hangs on Safari/MacOS

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#121]
Hello,
     I have the following setup:
         OS  10.11.6
        Safari 10.0.1 
        Flash 25.0.0.171
When I go to save a project locally, the Safari browser hangs with the spinning wheel.
A 0 byte file is created at the desired location.  There is no console output in the Web Inspector.
Safari has hung and it must be restarted.

This also happens with "normal" Scratch.mit.edu" projects.  
The problem doesn't occur with Chrome running the same Flash version as above.
Everything runs fine on older Safari/MacOS environments.

Is this happening to anyone else?

**Comment by chrisgarrity** [comment]
Moved to LLK/scratch-flash-online#318

**Comment by CreativeComputerLab** [comment]
Hi @chrisgarrity ,
     That link is broken.

**Comment by chrisgarrity** [comment]
@CreativeComputerLab we moved the bug to the internal Scratch team repo where it needs to get fixed to make sure it gets to the right person. Thanks for reporting it.

**Comment by scollovati** [comment]
Hi, 
I'm reporting the same issue.

macOS Sierra 10.12.2
Safari 10.0.2
Flash 26.0.0.131
