### ISSUE TITLE
Detect if Flash is Enabled in Browser

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#122]
Hello,
     The newer versions of browsers are disabling Flash by default. Is is possible to provide a pop-up to prompt the user  to enable Flash in their environment?
      While the solution is easy to remedy, it causes wasted time in classroom/ coding club scenarios where
the students are confused for a time. It would be easier on the instructor to have the Scratch App
inform the students about Flash so they can serve themselves.

**Comment by mkacct** [comment]
Although it probably won't be for a while, Scratch 3 will not use Flash so then it won't be necessary

**Comment by chrisgarrity** [comment]
@creativecomputerlab we appreciate the suggestion. As mentioned above, we're focused on Scratch 3.0 development which will not use Flash.
