### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by scollovati** [LLK/scratchx#126]
Hi,
I found that in the ScratchX interface there are some untranslated strings. 
Where I can find them? In [this file](https://github.com/LLK/scratchx/blob/gh-pages/locale/it.po) I cannot find them.

I refer, for instance, to the ones that appear when you want to load an extension.

**Comment by chrisgarrity** [comment]
@scollovati the translation strings are just for the Scratch editor on scratchx. Unfortunately none of the scratchx interface is translated. We plan to address this in Scratch 3.0.

**Comment by scollovati** [comment]
I'm writing here again since I'm translating to italian the Make Code Minecraft: Education Edition extension (https://github.com/scollovati/codebuilder-scratchx-ita).

I found that actually some simple strings (like left, right) are localized. Instead some strings (like forward, backward) are not.

It is my intention to fork this repo and then make a PR in which I'll add these 3-4 localized strings.
