### ISSUE TITLE
How to manage extensions' languages 

### ISSUE THREAD

**Issue by scollovati** [LLK/scratchx#127]
Hi, 
In order to translate an extension (see EV3 for example) I needed to create a new file and then translate the strings.

This, as you may think, creates a lot of problems: when you change the global language you need to change the URL; when you create an update to the code you need to remember to deploy it also to the other .js file in the different languages. 

Any suggestion on how to manage this?

**Comment by chrisgarrity** [comment]
@scollovati we're aware that scratchx extensions do not support translation. This won't be addressed until Scratch 3.0
