### ISSUE TITLE
Extension Does Not Load Automatically When Loading .sbx File

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#13]
Steps to Reproduce: 
1. Navigate to this URL to load project: 
http://scratchx.org/?url=http://creativecomputerlab.com/extensions/MakeSenseControlPanelAnalog.sbx

2. The project loads fine, however, the extension must be loaded in an extra step from:
http://creativecomputerlab.com/extensions/MakeSenseExt-v2.js.

3. A crosdsdomain.xml file exists at the root of the domain as per instructions in http://llk.github.io/scratch-extension-docs/#sharing-extensions:
http://creativecomputerlab.com/crossdomain.xml

More projects which exhibit the issue can be found at: 
http://creativecomputerlab.com/makesense-2.html#datamode

**Comment by khanning** [comment]
This is a result of issue #7  

As a workaround you can specify the extension along with the sample project in the URL.

i.e.
http://scratchx.org/?url=http://creativecomputerlab.com/extensions/MakeSenseControlPanelAnalog.sbx&url=http://creativecomputerlab.com/extensions/MakeSenseExt-v2.js

**Comment by CreativeComputerLab** [comment]
Beautiful Thanks Kreg!

**Comment by cwillisf** [comment]
Properly fixed with LLK/scratch-flash@a41e07ee40f0baa55588ae6bc98755d2b1e9f540 and LLK/scratch-flash@ce0a5e38082098d2211fcb77bce2500e4a4e1b4a
