### ISSUE TITLE
Don't work Text to Speech (UC Browser)

### ISSUE THREAD

**Issue by goosesima** [LLK/scratchx#132]
Don't talk text

**Comment by thisandagain** [comment]
We don't have any plans to support the speech extension with the UC Bowser at this time as it does not support the APIs needed for it to work:

![image](https://user-images.githubusercontent.com/747641/29496845-f1e97ace-85a8-11e7-99b7-db7cba9fff9f.png)

**Comment by goosesima** [comment]
):

20 авг. 2017 г. 20:08 пользователь "Andrew Sliwinski" <
notifications@github.com> написал:
