### ISSUE TITLE
ScratchX should allow extensions to be loaded from a local installation

### ISSUE THREAD

**Issue by jaafreitas** [LLK/scratchx#133]
Being able to run ScratchX and load extension without internet connection is important for places with little or no internet connectivity.

Steps to reproduce:
1) git clone https://github.com/LLK/scratchx.git
2) python27 -m SimpleHTTPServer 8001
3) Open ScratchX at http://localhost:8001
4) Choose your local extension in Open Extension URL. For example http://localhost:8001/scratch_extensions/helloworld.js

5) Do some work on ScratchX and save your project.
6) Open the project you've just saved.

scratchx.js:31 SWF Error: Refusing to load project extension "helloworld": Experimental extensions must be hosted on an approved domain. Approved domains are: .github.io, .coding.me
JSthrowError @ scratchx.js:31
(anonymous) @ VM2440977:1

There is a dirty workaround: you can tricky your hosts file and use extension.coding.me (for example) to resolve to 127.0.0.1.

**Comment by CvanLeeuwenFt** [comment]
At least to have the ability to load extension (Javascript) during the developing from a localhost or 127.0.0.1.
