### ISSUE TITLE
How to create a reporter block with checkbox?

### ISSUE THREAD

**Issue by CvanLeeuwenFt** [LLK/scratchx#137]
During a day I am looking around in the documentation but I could not find a description.
I only saw that it is possible but not "How to do" it.
How can I create in a extension a reporter block with the check box. So that the result shows up in the left top pane?
See also the images:
![reporterblock](https://user-images.githubusercontent.com/13519935/33915789-7ca9043a-dfa5-11e7-9675-4b4f5f4d982c.PNG)

I was able to reproduce the first one, the ',' with a space did the trick.
           ['r', 'loudness', 'getLoudness',  ],
However I was not able to find a solution for the second one:
            ['r' , 'Video %m.list1 on %m.list2 ' , 'getVideo' , 'motion' , 'stage' ,  ],
This code did  produce the reporter block but not the checkbox.

How to do it?
Where this is documented?

**Comment by mkacct** [comment]
AFAIK it will have a checkbox if it has no default values, and will not have a checkbox if it has any default values (`'motion' , 'stage'`)

**Comment by CvanLeeuwenFt** [comment]
However in the example, _part of the basic Scratch script "sensing"_, there are two default values.
list1 contains **'motion'**  and **'direction'** and list2 contains **'stage'**.
The block "current" in Sensing has as default 'month'.
![reporterblock2](https://user-images.githubusercontent.com/13519935/33916590-e36c4f66-dfa9-11e7-8b1d-d52501d6e20c.PNG)

**Comment by mkacct** [comment]
Built-in Scratch blocks are not created with a descriptor like extension blocks, so they would not have this restriction, but extensions (AFAIK) detect whether or not there can be a Stage viewer from whether or not there are any default values for the block's fields

also what is the "example" from?

**Comment by CvanLeeuwenFt** [comment]
How longer I am busy with developing an extension for Scratch how more restrictions I discover.
It looks like that Scratch don't like the developing of extensions.
Also the differences between the older HTTP based extensions and these JavaScript extensions.
See also my earlier comment on the HAT-blocks.

**Comment by CvanLeeuwenFt** [comment]
savaka2 Thanks for your fast comment on my problem

**Comment by thisandagain** [comment]
@CvanLeeuwenFt There is not a way to add monitor checkbox for extensions in Scratch 2.0 / ScratchX, but this is a feature that we will be supporting in the extensions spec for Scratch 3.0. You can see a preview of that here:
https://github.com/LLK/scratch-vm/wiki/Extensions-Proposal
