### ISSUE TITLE
Most images are missing an alt attribute

### ISSUE THREAD

**Issue by kerrtravers** [LLK/scratchx#138]
When looking through the code for the homepage and extensions page, I noticed that most of the extension images don't have an alt attribute.

**Comment by trafort** [comment]
It's not really important, The alt is just to put a text to show if the image is not loading.
But in your case, it could be important, to tell the user, the image is not loading.
:)

**Comment by kerrtravers** [comment]
@trafort Yeah, it also would be important if a scratch user (or somebody else that came across the site) was using text to speech on the page.

**Comment by trafort** [comment]
True, you click the image sometimes to go the project, if they see the alt word, they know what it is.
:D

**Comment by thisandagain** [comment]
Thanks @vutondesign. Good catch. This is important for accessibility. In your PR I would prefer to simply use the name of the extension rather than "`name of extension` Thumbnail".

**Comment by trafort** [comment]
He was just testing some things in his commit, I made the PR and he told me
@thisandagain

**Comment by kerrtravers** [comment]
@thisandagain No Problem, I will do 😃 

I've just noticed that a link to the main Scratch website is HTTP and not HTTPS, would you like me
 to throw that into this PR or make a separate issue for that?

**Comment by vutondesign** [comment]
@thisandagain I've just noticed that a link to the main Scratch website is HTTP and not HTTPS, would you like me to throw that into this PR or make a separate issue for that?

**Comment by thisandagain** [comment]
You can include it in this PR. Having it in a separate commit would be good
though. Thanks for asking.

**Comment by kerrtravers** [comment]
Okay 👍
