### ISSUE TITLE
variable number of arguments/parameter in blocks?  

### ISSUE THREAD

**Issue by frantic0** [LLK/scratchx#141]
Hello, 

From my exploration of the API I couldn't find anything related to defining blocks with a variable number of arguments/parameter or somehow passing a list as an argument. 

This might be feature request rather than a question. Is there any such feature available? If not, any plans for building support for it? 

Thanks

Best, 
Francisco

**Comment by thisandagain** [comment]
Hi @frantic0, we currently do not support blocks that have a variable number of arguments ("inputs"). We currently do not have any plans to support this as we feel it is confusing to users.
