### ISSUE TITLE
EV3 for Ubuntu

### ISSUE THREAD

**Issue by profshanks** [LLK/scratchx#143]
I am working with an elementary school to expand its coding and robotics program, and we would like to start using ScratchX to control Lego EV3 robots on laptops running Ubuntu (most likely running Firefox, but the browser choice is still up for debate). 

The missing link at this time is the device plug-in, which your website currently only posts install files for Mac and Windows.

If you would be willing to share the source files for either(or better yet both) of those install files, we could use them as a pattern to get the system working on an Ubuntu system. I have poked around a bit on your GitHub site, but I have not been able to find them.

Could you point me in the right direction?

Many thanks,
Sam Shanks (profshanks)
Duluth, MN

**Comment by thisandagain** [comment]
Hi @profshanks, we actually didn't produce the ScratchX EV3 extensions, but you can look at the source code from the author here:
https://github.com/kaspesla/ev3_scratch/

I hope that helps!

**Comment by profshanks** [comment]
Sorry. I already have the code for the EV3 extension. 

What I am looking for is the source code for the Scratch device plugin:

https://scratch.mit.edu/info/ext_download/

You have installers for Mac and PCs, but I would like to adapt this to work in Ubuntu.

That is the missing link for my project.

Many thanks for your help!
