### ISSUE TITLE
how to chanage display language go be japanese

### ISSUE THREAD

**Issue by TE-9004034667** [LLK/scratchx#146]
when i open the scratch page , it will display in japannese,
i think that is because my OS is japannese.

but when i use scratchX page ,it display in english.
how can i chanage to japannese?

**Comment by thisandagain** [comment]
Hi @TE-9004034667. You can use the "globe" drop-down in the top left corner of the screen to change the language:
![image](https://user-images.githubusercontent.com/747641/38497480-3b499b7c-3bcf-11e8-8dd3-07cb43a48c09.png)

Unfortunately the ScratchX website itself has not been translated.
