### ISSUE TITLE
can scratchx run by Command Line？

### ISSUE THREAD

**Issue by cooldeaaap1** [LLK/scratchx#158]
HI:
 We have a question that: we want to run a scratchx job auto . But.now we have to click that green button . 
so ,is there a way to make it run in Command Line?

**Comment by CreativeComputerLab** [comment]
Hi,
     We have the same requirement. We want to start a ScratchX project running on system boot.

**Comment by thisandagain** [comment]
There currently isn't a way to "click the green flag" via the console. Sorry about that folks! This is something you will be able to do in Scratch 3.0.
