### ISSUE TITLE
"ScratchEd" and "ScratchJr" in the navigation bar points to the wrong website.

### ISSUE THREAD

**Issue by Rumanti** [LLK/scratchx#16]
Both "ScratchEd" and the "ScratchJr" links on the navigation bar points to http://scratch.mit.edu (Scratch's main site) when they are supposed to link to http://scratched.gse.harvard.edu/ (ScratchEd) and http://www.scratchjr.org/ (ScratchJr).

**Comment by rschamp** [comment]
Thanks for the catch!
