### ISSUE TITLE
Old style

### ISSUE THREAD

**Issue by animagod** [LLK/scratchx#162]
Needs to be updated to look like 3.0

**Comment by towerofnix** [comment]
The readme of this repository says this:

> Note: Scratch 2.0 and ScratchX are now in maintenance mode while the team focuses efforts on Scratch 3.0. While critical issues will be addressed please note that any feature requests or minor issues will not be reviewed until the next major release.

ScratchX will not be updated to look like 3.0. Instead, Scratch 3.0 will (as far as we know) eventually support community-submitted extensions, as well as loading extensions from JS file URLs, which is very similar to ScratchX. These are both still a ways off though.
