### ISSUE TITLE
(Feature Request) Can you make a offline program that isn't a web server?

### ISSUE THREAD

**Issue by ghost** [LLK/scratchx#164]
Can you add a offline program that isn't a web server, because the website is insecure and i wan't to make my project while not having a internet connection like the original Scratch program but you can download extensions and use them with scratchx?

**Comment by GrahamSH-LLK** [comment]
This isn't going to be acted upon soon. See 
![image](https://user-images.githubusercontent.com/64214252/80852530-4dff9580-8bf7-11ea-8c43-51b264d84292.png) The scratch team isn't updating or adding any new features right now.

**Comment by ghost** [comment]
sorry

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
