### ISSUE TITLE
Flash Player is Going out and Scratch 2.0 and ScratchX is doomed

### ISSUE THREAD

**Issue by ghost** [LLK/scratchx#165]
We should update ScratchX to 3.0 standard or switch to Javascript/HTML5 technology

**Comment by daniel4-scratch** [comment]
This could be accomplished since Adobe Flash is cancelled now.
But we really don't need to use ScratchX any more, we are moving on to 3.0 
But you can still download Scratch 2.0 on the Scratch website; https://scratch.mit.edu/download/scratch2

**Comment by FunctionalMetatable** [comment]
How do we make extensions then? will there be an official mod/page to test our extensions?

**Comment by daniel4-scratch** [comment]
You don’t, the internet is moving on to something new. **Every thing can’t live forever**.
