### ISSUE TITLE
Micro:Bit V2 support on Scratch 3.0

### ISSUE THREAD

**Issue by trunifom** [LLK/scratchx#167]
Hi guys

Our university is developing a new course for schools using Micro:Bit V2. Now we would like to send sensor data to Scratch in our projects.

1. Are you already working on sending sensor data from the Micro:Bit V2 to Scratch?
2. Does it make sense to develop a separate extension for the Micro:Bit V2?
3. If not, can I help you with this?

Regards
Dominique

--
Dominique Truninger
ZHAW, Zurich University of Applied Sciences
InES, Institute of Embedded Systems
Technikumstr. 9
CH-8401 Winterthur
--
Tel: +41 58 934 45 34
E-Mail: dominique.truninger@zhaw.ch
Web: http://ines.zhaw.ch
--

**Comment by ericrosenbaum** [comment]
Hi- this repository (scratchx) is effectively obsolete now that Flash is no longer available. I'll investigate closing the issues and PR sections. You can post questions about official scratch extensions at https://github.com/LLK/scratch-vm.

Re: micro:bit v2, as of November 2020, Scratch is compatible with microbit versions 1 and 2. We provide a hex file containing microbit firmware v1.2.0 that works on both microbit v1 and v2, on our microbit [page](https://scratch.mit.edu/microbit).
