### ISSUE TITLE
Github link on landing page doesn't lead to scratchx repo

### ISSUE THREAD

**Issue by mewtaylor** [LLK/scratchx#18]
Looks like the link currently is to https://github.com/LLK/. Should it be to the scratcx repo specifically, i.e. https://github.com/LLK/scratchx?

**Comment by technoboy10** [comment]
IMO, it doesn't necessarily have to - since the GH icon is next to the Twitter icon, it's sort of implied that the links will be to the social profiles of Scratch/LLK.
