### ISSUE TITLE
Text changes on ScratchX 

### ISSUE THREAD

**Issue by kaschm** [LLK/scratchx#19]
* For the main description on the landing page, change “electronic devices and kits” to “electronic devices and robotics”

* For the warning dialog when you enter the editor, change to:
Warning: The extensions on this site are experimental
The Scratch Team is not responsible for the extensions and projects on this site. Please use caution when using these extensions. Learn more.

* Homepage, Open an Extension File becomes 'Open an Extension Project'

**Comment by kaschm** [comment]
lightning fast @rschamp !

**Comment by rschamp** [comment]
;)
