### ISSUE TITLE
Feature the much more "feature"ful mesh extension :-)

### ISSUE THREAD

**Issue by bobbybee** [LLK/scratchx#2]
https://cdn.rawgit.com/bobbybee/mesh-2.0/67f866ac702b13e6bea2891cff0fb7a7a1b08a35/ext.js

**Comment by cwillisf** [comment]
Hi @bobbybee. We haven't quite decided how and when we want to update the featured extension list, but if you'd like your extension to be more visible you're more than welcome to add it to the list on the ScratchX wiki:
https://github.com/LLK/scratchx/wiki/Example-Extensions
Thanks!
