### ISSUE TITLE
Scratch Browser Plugin crashes on Windows 8.1

### ISSUE THREAD

**Issue by khanning** [LLK/scratchx#30]
The plugin crashes while trying to load a project that uses the Scratch Browser Plugin on Windows 8.1

<b>Chrome 43:</b> The editor fails to load and instead displays the "Aw Snap!" error message
<b>Firefox 38.0.1:</b> The editor fails to load and `TypeError: Scratch.FlashApp.$ASobj is undefined` is output to the console.

If I disable the plugin, the ScratchX editor loads fine.

**Comment by khanning** [comment]
I should also point out that this issue occurs on regular Scratch. I just posted the issue here for visibility.

**Comment by cwillisf** [comment]
On my machine (Windows 8.1, Chrome 43, Firefox 31.7 ESR) the plugin is working fine on the main Scratch site but is broken on ScratchX.

I don't get a crash, but device communication isn't working correctly either. For example, the status indicator for the WeDo plugin turns green but the blocks can't read the distance sensor or turn the motor on.

**Comment by programitra** [comment]
I have run into this issue too, my 8.1 machine crashes and reboots while trying to load the extension. Its working on windows 10.
