### ISSUE TITLE
Change plugin DL link

### ISSUE THREAD

**Issue by kaschm** [LLK/scratchx#31]
on homepage:

Note: To use any physical extensions, you need to download the Hardware Plugin.

'Hardware Plugin' should point instead to:
https://scratch.mit.edu/info/ext_download/

**Comment by MrYsLab** [comment]
My extension, Xi does not require the hardware plugin. It would be great if the informational dialog box to load the plugin could be made optional.

**Comment by cwillisf** [comment]
@MrYsLab sorry about that... we'll be improving various aspects of the extension system, and we'll try to find a good solution to issue #25 as we do that.

**Comment by cwillisf** [comment]
This issue was fixed with 33b44ceeba2245aa682085bb666cd5d1bbfd28e3
