### ISSUE TITLE
Saving a ScratchX project doesn't overwrite existing .sbx file

### ISSUE THREAD

**Issue by khanning** [LLK/scratchx#32]
If you attempt to download a ScratchX project twice, the second download does not overwrite the first one. Instead '.sbx' is appended twice to the filename. A dialog should popup asking if you want to replace or cancel.

Steps to reproduce:
1. Create a project on ScratchX
2. Save the project with `File > Save Project`
3. The file is saved with the name `ProjectName.sbx`
3. Save the project again with `File > Save Project`
4. The file is saved with the name `ProjectName.sbx.sbx`

**Comment by MrFlash67** [comment]
Safari 8.0.6, Mac 10.10.3, it's there.
![screen shot 2015-05-29 at 12 59 41 pm](https://cloud.githubusercontent.com/assets/4315979/7874364/a05cbb08-0602-11e5-83de-d597cdc5bef9.png)

**Comment by chuckuntulis** [comment]
I have seen the same problem and I agree with your suggestions.
