### ISSUE TITLE
Text changes on homepage

### ISSUE THREAD

**Issue by kaschm** [LLK/scratchx#33]
This is correcting something which is incorrect regarding the plugin. 

Change 'Any' --> 'Many' in description of device plugin download:

Note: To use any physical extensions, you need to download the Hardware Plugin.

**Comment by savaka2** [comment]
Where does it say this? All I see is "Most physical extensions require the Scratch Device Plugin - Download here"

**Comment by mewtaylor** [comment]
@kaschm this appears to have been solved: https://github.com/LLK/scratchx/blob/gh-pages/index.html#L79. It's not the same text, but has same message. Is that correct?

**Comment by savaka2** [comment]
@mewtaylor yeah that's what I was referring to. The word "Any" doesn't even appear anywhere referring to the Scratch Device Plugin.

**Comment by kaschm** [comment]
@mewtaylor @savaka2 - good catch. Yes, this was solved via https://github.com/LLK/scratchx/blob/gh-pages/index.html#L79 ... closing this issue.
