### ISSUE TITLE
Editor doesn't load in FF Linux

### ISSUE THREAD

**Issue by seotts** [LLK/scratchx#35]
Here is the console:
![image](https://cloud.githubusercontent.com/assets/4612592/8010085/46fcb04e-0b7b-11e5-8409-102954706953.png)

**Comment by 2jour** [comment]
Can reproduce on Ubuntu.

**Comment by MrYsLab** [comment]
Duplicate of #24

**Comment by thisandagain** [comment]
Tracking in #24
