### ISSUE TITLE
Arduino servo

### ISSUE THREAD

**Issue by chuckuntulis** [LLK/scratchx#36]
After a lot of experimentation, I was finally able to get the following code to run - http://screencast.com/t/3pQu4Nu7 - generating a pop and moving the servo between two positions. I did a Save Project to the local file system.

The green light is still on and when I do a File>Load Project from the local file system, the code is loaded and the green light is changed to yellow. The code runs and I hear the pop, but the servo does not move.

What is the proper way to Save the project and then Load the project and have the servo work? 

Is there an example where the code is loaded and ScratchX is connected to the Arduino so that the code will run and move the servo?

I touched the servo and it is very hot. I unplugged the Arduino and the servo cooled down.

Thanks

Chuck.

**Comment by khanning** [comment]
@chuckuntulis I was not able to duplicate your results using Chrome on OS X 10.9.5. Can you share some details about the system you are using.

Just to be clear, these are the steps I tried:
1. I ran the same Scratch blocks you provided in the screenshot with an Arduino UNO connected to USB and a servo motor connected to the Arduino's +5v, GND, and pin 9. 
2. I click the green flag, servo starts swinging back and forth
3. With the Arduino still connected (indicator light green) I click File > Save Project and download the .sbx
4. With the Arduino still connected I click File > Load Project and load the .sbx file
5. I click the green flag, servo starts swinging back and forth

In the Arduino extension [Example Projects](http://khanning.github.io/scratch-arduino-extension/#examples) there's an example titled [Swing a Servo](http://scratchx.org/?url=http://khanning.github.io/scratch-arduino-extension/arduino_extension.js&url=http://khanning.github.io/scratch-arduino-extension/examples/Arduino%20Example%20-%20Swing%20a%20Servo.sbx) that demonstrates using a servo motor with the Arduino extension.

**Comment by chuckuntulis** [comment]
Thanks. I will try that.

 

Chuck

**Comment by chuckuntulis** [comment]
Hi Kreg,

 

Thanks again for your message. 

 

I am running Windows 7. 

 

The behavior is the same as steps 1-3 below. However when I File > Load Project, the button stays yellow and there is no servo movement even after waiting about 5 minutes. I tried the File > Load Project many times and each time, when I do the Load Project it changes the button to yellow and never turns it back to green.

 

Are there any plans to have an explicit reconnect? It really seems to be necessary for Windows since reloading does not seem to work. There needs to be some way to report the state and why attempts are failing.

 

Are there any plans to have variables that can be defined and used in the Arduino blocks, Control blocks and the other blocks? Are there any plans to have Methods or Funtions so that students can build up higher order thinking?

 

I am afraid that without those and the ability to consistently reload code that the Arduino code is not going to be very useful except for some simplistic examples.

 

I have spent a lot of time mentoring middle school and elementary students in Robotics. I was hoping the ScratchX might be useful for that purpose, but I have my doubts. 

 

Thanks again.

 

Chuck

**Comment by ntlrsk** [comment]
@chuckuntulis Just making sure - do you have the latest version of the Scratch extension plug-in?

**Comment by chuckuntulis** [comment]
Today I downloaded the latest version of the Scratch Extension.

 

I still am seeing anomalies.

·         If I load the previously saved code and then load the Arduino Extension, it never connects to the Arduino and I have no idea why - there are no status messages or displays to tell me what might be happening

·         As far as I know, there is still no way that I can define a Script block to explicitly connect to the Arduino

·         If I go to scratchX.org and then Open a Extension Project that I saved earlier, it eventually connects to the Arduino and runs my script following the "when device is connected" block

·         I have been surprised a couple of times when ScratchX disconnects from the Arduino for no apparent reason.

 

Is there a protocol for loading two or more projects so I can essentially debug part of the code and reuse it?

 

Thanks

 

Chuck

**Comment by khanning** [comment]
@chuckuntulis I was able to test this today on Win 7 and I am seeing the same behavior as you. If you remove the extension and then re-import it while the same project running, the device is not able to reconnect. This appears to be an issue with the Scratch Browser Plug-in which would affect all JavaScript extensions that use serial communication. As a temporary workaround you should be able to just refresh the page before loading the .sbx file.

```
As far as I know, there is still no way that I can define a Script block to explicitly connect to the Arduino
```
There are no blocks to connect/disconnect the Arduino. The extension attempts to automatically connect to the Arduino. If you think there should be blocks specifically for connecting/disconnect please [submit it as an issue](https://github.com/khanning/scratch-arduino-extension/issues/new) on the [Arduino extension GitHub repo](https://github.com/khanning/scratch-arduino-extension).

```
If I go to scratchX.org and then Open a Extension Project that I saved earlier, it eventually connects to the Arduino and runs my script following the "when device is connected" block
```
 This is the expected behavior. The time it takes to connect will depend on the number of serial ports on your system. The extension gives up and moves to the next serial port after 5 seconds. When the extension successfully connects to the Arduino the "when device is connected" block is executed.
```
I have been surprised a couple of times when ScratchX disconnects from the Arduino for no apparent reason.
```
I have not seen this yet. Any steps I can take to try to replicate this? What is connected to the Arduino at the time? How long does it run before it disconnects?

Thanks for the feedback!

**Comment by chuckuntulis** [comment]
Hi Kreg,

 

I am looking through the code again and I have some questions (documentation suggestions)

·         I see this line "console.log('Attempting connection with ' + device.id);" but I do not know where that is displayed?

·         Is there a reason that there is no "reconnect" block or no "connect" block? It looks like the code is there to implement it and is executed at "init"?

·         What do servo A,B,C,D correspond to?

·         Is there a reason to limit the servo list to four servos? I see this line

·         Similar questions for buttons?

·         How can new students add more servos, buttons?

·         Is there a reason that there are no servoOn and servoOff blocks? At present the servo, runs forever. I figured out that "set pin" to off/on turns off/on the servo. This would make it easier for new students

·         Why are there ext.rotateSrervo and function rotateServo?

·         Are there plans to add comments to the scrartch-arduino-extension code?

·         Are you planning to add more blocks and what might they be?

·         I see stepper, encoder and I2C in the vars list but no code. Are you planning to add blocks for these?

·         Are you planning to add blocks for other sensors to make it easier for new students to understand?

·         Are you planning to add a "show code" block so that students can look at what is happening under the covers and gain a better understanding about coding details.

 

I would attempt some of these but I do not know what is in the pipeline or how they would be received.

 

Thanks

 

Chuck
