### ISSUE TITLE
SBX project can't load more than one extension

### ISSUE THREAD

**Issue by Znapi** [LLK/scratchx#37]
If you load multiple extensions into a .sbx project and save it, when you reopen it, only the last extension loaded in will load. The rest of the extensions don't.

**Comment by ericrosenbaum** [comment]
I've encountered this problem as well. Here's an example:

The voice controlled car project [here](http://scratchx.org/?url=https://ericrosenbaum.github.io/scratch-extensions-1/speech%20io%20%2B%20wedo%20car%20test.sbx#scratch) should load the WeDo extension and the Speech IO extension ([here](https://ericrosenbaum.github.io/scratch-extensions-1/speech_io_extension.js)), but sometimes only loads the WeDo extension

**Comment by GrahamSH-LLK** [comment]
This has happened to me.
