### ISSUE TITLE
Reporter callback doesn't exist

### ISSUE THREAD

**Issue by GrannyCookies** [LLK/scratchx#39]
When using 'R' blocks, a callback is supposed to be passed as a parameter... it doesn't seem to work.

**Edit: This happens on the [Scratch Website](https://scratch.mit.edu), not ScratchX**.

**Comment by khanning** [comment]
It appears to be working fine for me. The callback is being passed to the function in the following example:
```
ext.waitThenAdd = function(a, b, callback) {
  setTimeout(function() {
    callback(a+b);
  }, 1000);
};

var descriptor = {
  blocks: [
    ["R", "wait then add %n + %n", "waitThenAdd", 2, 3]
  ]
};
```

Can you provide any more details on what is not working for you? Example code would be great!

**Comment by GrannyCookies** [comment]
Hm... well, this happens on the normal Scratch website, at least.
Here's the code:
```js
var descriptor = {
    blocks: [
        ['R', 'get key %s of user %s', 'get', 'foo', 'lightnin'],
    ]
};

ext.get = function(key, user, callback) {
    console.log('got arguments: ', arguments);
    $.get('https://example.com/api/test.json', function(data) {
        callback(data);
    });
};
```

**Comment by GrannyCookies** [comment]
Seems fixed now. Thanks.
