### ISSUE TITLE
PicoBoard connection not reliable

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratchx#41]
From a user on Windows 7 using Firefox on the main Scratch site:

> We’ve been using Firefox. Typically, we like to use Google Chrome, however after installing the PicoBoard plugin (it is a .MSI file), the PicoBoards still would not connect. So we switched over to Firefox, which seems to be working a bit better for us.
> 
> Most cases, the first time we open a browser and connect the PicoBoard, the indicator is red or yellow. So we then have to close the browser and start again. Once we’ve done this, the indicator is green when we connect the PicoBoard and the students are set to code. Unfortunately, if the students save, close out of the editor, and try to work on this project again at a later time, the indicator is red and the PicoBoard does not connect anymore. Our solution for this is to backpack every sprite (with it’s codes) and then transfer them to a new editor page. Here we can connect the PicoBoard and continue coding.

**Comment by cwillisf** [comment]
Speculation:
- The Chrome vs. Firefox comments may be related to #22.
- A red status indicator when opening an existing project may indicate that we're failing to remove lock table entries under some circumstances, possibly specific to Firefox and/or Windows 7.

**Comment by 2jour** [comment]
Is this still an issue? @cwillisf ?
