### ISSUE TITLE
Is it Possible to For Scratchx to Load Extensions from the Local File System?

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#43]
Hi, I've created a standalone web server to serve Scratchx in environmnets without an internet connection. Now I wish to be able to load extensions from the local file system in the same manner as loading a local .sbx file. Is it possible to make a mod so that I get a local file chooser dialog when I choose to load an extension?

**Comment by Thepuzzlegame** [comment]
You can already load extensions locally by right-clicking or shift-clicking the "Load Experimental Extension" button.

**Comment by CreativeComputerLab** [comment]
Purrfect. Thanks!
