### ISSUE TITLE
Can The Sprite Library be Generated in Scratchx Running on Local Webserver? 

### ISSUE THREAD

**Issue by CreativeComputerLab** [LLK/scratchx#45]
Hi,
   I am running a local version of Scratchx in rural schools w/o broadband as per issue #38 and
it is working fine, thanks! However, I'm finding the missing sprite library quite a nuisance to younger
students. Is it possible to generate the sprite library in the same manner as done in the Scratch2 offline editor? Specifically in the Scratch2/media/libs dir there is a Python script named "generate-costume-library.py" which appears to be processing all of the sprites in the media lib. Is there a way to run this process in my local web server on its local copy of the Scratch2/media/libs dir so that the sprite library renders in the local webserver version? I am willing to modify source code if necessary.

**Comment by bybb** [comment]
I would say if you could look through the python file and compile it by hand into php it might work. If it doesn't (which is highly likely) you will just have to have to have your students make all of the sprites.

**Comment by kenken64** [comment]
Anyone solution for this issue? I am having the same problem as well.

**Comment by cwillisf** [comment]
The `generate-costume-library.py` script may not be very useful to you as it is. Its job is to read `spriteLibrary.json` and "flatten" it into a list of individual costumes, then store that list in `costumeLibrary.json`. It does provide an example of how to parse these JSON files, though.

Unfortunately we're not able to include the sprite library in this repository for copyright & trademark reasons. However, I suggest looking at the following:
* The `urlOverrides` section of [scratchx/js/scratchx.js](https://github.com/LLK/scratchx/blob/3b51d345cfe190130918a1316da37f50b3e85f3b/js/scratchx.js#L90), and
* The `media` folder inside an installation of the [Scratch 2.0 Offline Editor](https://scratch.mit.edu/scratch2download/).
