### ISSUE TITLE
Any way to update menus in blocks?

### ISSUE THREAD

**Issue by davidferguson** [LLK/scratchx#47]
I am creating a ScratchX extension, and have the code

var descriptor = {
    blocks: [
        [' ', 'Connect to IP %m.ipSelection', 'ipConnect', 3]
    ],
    menus: {
        ipSelection: ['Loading IPs, please wait...']
    },
};

as my descriptor object. I basically want the user to choose from a list of IP addresses to connect to.

However, my problem is that the IP addresses take a few seconds to load into my js file, and when I use the code

descriptor.menus.ipSelection = newIPs;

to try and update the menu in the block, it updates the descriptor object, but not the contents of the menu in the block.

Is there a way for me to be able to update the menu inside one of the blocks?

Thanks

**Comment by bleush38p** [comment]
As far as I'm aware, there's not a way to update it live. You can still remove and re-add the extension to get similar behavior. The [Cookie Variables extension](https://scratch.mit.edu/discuss/topic/65698/) uses this technique, creating a very neat effect.
