### ISSUE TITLE
Can't get ScratchX to run on any browser with hardware devices

### ISSUE THREAD

**Issue by Mariam8787** [LLK/scratchx#48]
I am having a problem using ScratchX with hardware devices either Lego Wedo or Arduino. In both the problem is the same, the hardware device is connected to the laptop but it always show the yellow circle on ScratchX project. What might be the problem ?

Thanks

**Comment by 2jour** [comment]
What operating system are you using @Mariam8787 ? 

One thing to try is to upgrade to the latest plugin https://scratch.mit.edu/info/ext_download/

Let us know if this works

**Comment by Mariam8787** [comment]
Well, I can't thank you enough. I have been in this problem for a year now (first with lego wedo and now with Arduino) and now it's solved after upgrading the plugin.

For Arduino it solved it on Firefox but not on Chrome, but it's pretty fine.

Thank you.
