### ISSUE TITLE
Please add x(close) button on 'Load Experimental Extension' dialog.

### ISSUE THREAD

**Issue by ByeongsuKim** [LLK/scratchx#49]
I am making scratchx + arduino app.
Arduino extension example of scratchx main site only works in firefox browser now.
(Chrome doesn't support NPAPI now.)

So I have a idea to make this can work in any browser using nw.js.

But, When I click ''Load Experimental Extension' in chromium or explorer, they stopped.
I guess modal(?) css can't work well in these browser.

Do you have any idea to close this dialog(full screen blue dialog) ?

If it's not possible, 
Please add x(close) button on 'Load Experimental Extension' dialog.

Blue screen looks like below.
http://www.codeme.kr/x4a/screen.png

**Comment by thisandagain** [comment]
Hi @byeongsukim, if you click on the background the dialog should disappear. Is this not working for you?

**Comment by ByeongsuKim** [comment]
When I use node-webkit(nw.js), it doesn't work.
2016. 1. 7. 오전 12:03에 "Andrew Sliwinski" <notifications@github.com>님이 작성:
