### ISSUE TITLE
Spaces in project name show as '%20' in scratchx editor

### ISSUE THREAD

**Issue by khanning** [LLK/scratchx#5]
If I open an example project that contains spaces in it's name, the spaces appears as %20 in the scratchx editor window (see screenshot).

Example project:
http://scratchx.org/?url=http://khanning.github.io/scratch-arduino-extension/examples/Arduino%20Example%20-%20Adjusting%20LED%20with%20Rotation%20Knob.sbx

![screenshot](https://cloud.githubusercontent.com/assets/1169507/7549766/c51179ca-f612-11e4-9b04-ef703db24d30.png)

**Comment by cwillisf** [comment]
Fixed with LLK/scratch-flash@2097a081b2e963379ee365a28fea69ec96ccb683
