### ISSUE TITLE
Arduino disconnected

### ISSUE THREAD

**Issue by louiswolf** [LLK/scratchx#52]
Edit: 
It seems Chrome dropped NPAPI support. The Arduino Scratch extension needs to support PPAPI in order to work on future versions of Chrome.

---

ScratchX won't connect with the Arduino on Windows 8.1 / Chrome 45 (Yellow connection icon in ScratchX), even with the 'previous' plugin version as mentioned in the docs. On the same configuration, Leap Motion does work with ScratchX.

The browser console keeps mentioning: "Attempting connection with COM8". 
The board's LED's blink in a relatively complex but repeated pattern which seems to be:

L - Twice
RX - Once
L - Twice
L - Once
RX - Once
L  - Three times
TX - Once (short)
RX - Once (short)
TX and RX simultaniously - Twice

I'm not sure if the above is of much use, but let me know if you need additional information.

**Comment by cactrot** [comment]
I've been trying to get around this problem too. I have been trying to write a chrome extension/App that can access the serial port and use the native messaging interface to connect with scratch. But I can't find any reference on the protocol. I have figured out how to get up to "serial_recv_start". The data I send back gets as far as the "serialRecv" handler in scratch_nmh.js but doesn't get passed to the arduino_extension.js extension. It seems like "set_receive_handler" isn't getting caller for some reasion. Hopefully the source for the scratchx.swf will be posted at some point and I can figure out what I'm missing.

**Comment by Haitham11228** [comment]
I have the same problem , and i could not find a solution for this problem , it works in Safari but not in Chrome.
