### ISSUE TITLE
Scratch Device Plugin Crashes when stopBits is set to 1

### ISSUE THREAD

**Issue by jdorich14** [LLK/scratchx#53]
When trying to open a serial device using this:

```
"device.open({ stopBits: 1, bitRate: 115200, ctsFlowControl: 0 });"
```

the Scratch Device Plugin crashes and reports this in the browser console:

> "Error opening serial device COM23: Error: Error calling method on NPObject!"

If stopBits is set to 0, it works fine.

I am using Mozilla Firefox 40.0.3 and Scratch Device Plugin 2.1.2.1 on Windows 7.

**Comment by DangeRuss1313** [comment]
I'm having the same issue using Chrome 45.0.2454.101 and Scratch Device Plugin 2.1.2.0 on Windows 7.
