### ISSUE TITLE
Chrome: serial receive handler called twice per read

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratchx#55]
From @khanning:

> I received a couple of reports that the Arduino extension isn't working properly with Chrome. After taking a look at the issue it seems like the receive handler is being called twice each time data is read.
> 
> To test this, I set up an Arduino with a simple firmware that starts at 0, increments by 1 each second, and writes the digit to the serial port. Everything behaves as expected on Firefox, each digit is received by the receive handler (0 1 2 3 4 ...). However, on Chrome each digit gets received by receive handler twice (0 0 1 1 2 2 3 3 ...). I was able to confirm this behavior on both OS X 10.9 and Windows 10 with the latest version of Chrome and the Chrome helper/device host plugin. 

This would not be very disruptive to the PicoBoard, but I'm sure there are many devices and protocols which would not function in these circumstances.

**Comment by vorpalrobotics** [comment]
In case this helps, I was able to write an extension to control a robot over serial (to an HC06 bluetooth module) using Google Chrome on windows 10.  The trick was, sending data over the serial port works just fine, you just can't get any data back from the serial port. So, this works as long as you only have one serial device so there's no confusion about which COM port to use.

In debugging this, I found that my receive data handler is NEVER called. I wrote a very simple one that simply writes out to the console log.

So, any of you who could use a one-way serial connection, it does work in chrome right now on windows 10.

I'm hoping that pointing this out will help the plugin developers on chrome find the issue. Something stops data from going back up to the scratch script, but scratch can send data just fine, so the serial port is indeed opening and operating to some extent.
