### ISSUE TITLE
Load Experimental Extension doesn't work locally

### ISSUE THREAD

**Issue by Jxr227** [LLK/scratchx#57]
So on the scratchx website you can right click to load a local experimental extension, however I've noted this doesn't work when running this locally.

**Comment by khanning** [comment]
How are you running ScratchX locally? Right click and Shift + click to load a local extension works for me while running ScratchX locally using the Python HTTP server module.

**Comment by 2jour** [comment]
Hi Jxr227,

Are you still having problems loading extensions locally? If so, could you let me know what browser and OS you are using ?

**Comment by Jxr227** [comment]
Sorry only just came back to this. It was me being a bit of an idiot not running the server. Of course without the python HTTPServer the webpage will load but the resources it runs doesn't. Apologies for wasting any time, closing!
