### ISSUE TITLE
No tips window

### ISSUE THREAD

**Issue by savaka2** [LLK/scratchx#70]
When an extension has red status indicating that you don't have the necessary plugin, the same message is used as on Scratch telling you to look at the tips window, but ScratchX has no tips window.

**Comment by savaka2** [comment]
I made a better issue: #79

**Comment by liam4** [comment]
You could have edited this one.. :P

**Comment by savaka2** [comment]
@liam4 The issues are kind of opposites though, because this issue is about that the dialog should be changed because there is no tips window, and #79 is about that the tips window should be added because the dialog says to look at it.
