### ISSUE TITLE
Extension boilerplate IIFE has unnecessary { } tokens?

### ISSUE THREAD

**Issue by darren-a** [LLK/scratchx#72]
The function expression that kicks everything off has this form:

( function(ext) { /\* code here */ } )  ( { } );

the last two curly braces are not needed, AFAIK.

Crockford recommends:

( function(params) { /\* code here */ }  ( )  );

and I've seen this:

( function(params) { /\* code here */ } )  ( ) ;

If there's no explicit reason for the curly braces I suggest they be removed so the code looks more like code that people will see in other places. (I'd vote for Crockford's way as it keeps everything 'function-y' inside the bracketed expression.)

**Comment by darren-a** [comment]
Forget this - my confusion. I see that it's the empty object that the extension code is going to add methods etc to.

I was expecting either nothing, or some kind of value.

I'm still not quite clear on why we need to pass an empty object in as an argument. Would it not be possible to create our extension object at the start of our main function and still register it using ScratchExtensions.register?

I'm probably still missing something here...

**Comment by Znapi** [comment]
I don't think it matters how you create the extension object. [The Xi extension](https://github.com/MrYsLab/xi/blob/master/clients/scratch/xi4s/xi4s.js) doesn't use the way that the wiki says to.

**Comment by darren-a** [comment]
Thanks!

Wow, many ways to skin this cat. He or she used a constructor.

I used this for a test extension and it seems to work ok:

(function() {

    var ext = {};

    // code here

} ) ();

It only made sense to me to pass in an argument to a function if that argument is something that can't be known or created from the inside.

The reason I'm asking the question (apart from learning myself) is because I'm writing slides for people coming to ScratchX with little to no JS experience and I think this construction could be a little confusing, given that it seems to be a slightly unusual twist on the IIFE pattern.
