### ISSUE TITLE
Add docs for displayName

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratchx#76]
As of https://github.com/LLK/scratch-flash/commit/30d11fa3808c74a8141a4eb9b9921e5a5fe16b62 extensions now support a new property (alongside `url` etc) called `displayName`. This hasn't been added to the wiki yet.

**Comment by liam4** [comment]
There's also https://github.com/LLK/scratch-flash/pull/1032 which will need to be updated.

It looks like everybody has access to editing the wiki page, so I might look into documenting these new features..

**Comment by towerofnix** [comment]
[I documented `displayName`.](https://github.com/LLK/scratchx/wiki#display-name) I didn't bother with forced-async blocks, since I'm not entirely sure how they work, and Scratch 2.0 extensions probably aren't going to be around all that longer, with the entirely new system in 3.0.
