### ISSUE TITLE
Trigger an event on stop button press

### ISSUE THREAD

**Issue by Jxr227** [LLK/scratchx#77]
Hi,
Is there currently a way to do the title? My extension uses setInterval loops to control an agent, so for instance it could move for 100 seconds, however the nature of the loop means that it continues running even when the stop button is pressed. Is there any functionality so that I can call clearInterval() everytime the stop button is pressed?
The only semi-solution I've implemented is having my own "Stop" block, however it only stops currently running loops, and doesn't end the entire program.

Thanks

**Comment by bjpirt** [comment]
+1
This is particularly handy when interacting with external hardware. I think the user would expect the external hardware to stop as well as the code.

**Comment by khanning** [comment]
You are now able to detect when the stop button has been pressed by using the ext._stop function.
```
ext._stop = function() {
  console.log("stop sign has been clicked!");
};
```

**Comment by savaka2** [comment]
This seems to also trigger when the green flag is clicked

**Comment by Jxr227** [comment]
No longer actually required but glad to see this made it as a feature! Will try to tinker with it when I get the opportunity.
