### ISSUE TITLE
Fix "enforsed"

### ISSUE THREAD

**Issue by savaka2** [LLK/scratchx#88]
you seem to ignore pull requests on this repo?
I'm going to make issues for them then?

Fix "enforsed" at [line 97 of index.html on gh-pages](https://github.com/LLK/scratchx/blob/gh-pages/index.html#L97)

PR assuming the correct word should be "endorsed" is #73

**Comment by thisandagain** [comment]
We'll take a look! Thanks for reporting and sending along PRs!

**Comment by savaka2** [comment]
Resolved in #73
