### ISSUE TITLE
Remove FAQ link

### ISSUE THREAD

**Issue by savaka2** [LLK/scratchx#89]
Delete a tag linking to FAQ page from FAQ page because you just click it and it does nothing because you're already on the FAQ page at [line 453 of index.html on gh-pages](https://github.com/savaka2/scratchx/blob/gh-pages/index.html#L453)

PR is #80

**Comment by thisandagain** [comment]
O_o Good catch!

**Comment by savaka2** [comment]
Resolved in #80
