### ISSUE TITLE
Arduino 101 question

### ISSUE THREAD

**Issue by savaka2** [LLK/scratchx#91]
this is a question

How is the Arduino 101 extension at https://llk.github.io/arduino-101/arduino101_serial_extension.js when there is no repository LLK/arduino-101 or LLK/LLK.github.io?

**Comment by thisandagain** [comment]
The repo is still closed, but we will be opening it soon!

**Comment by savaka2** [comment]
by closed do you mean private?

**Comment by thisandagain** [comment]
Yes.

**Comment by savaka2** [comment]
ok
