### ISSUE TITLE
How do you use things that scratch already has? IE current pen cool

### ISSUE THREAD

**Issue by NitroCipher** [LLK/scratchx#94]
What are the codes needed to use stuff such as the current color of the pen tool, project variables, etc?

**Comment by liam4** [comment]
Basically.. hacks.

Here's how you can get the current project object:

```js
JSON.parse(decodeURIComponent(Scratch.FlashApp.ASobj.ASgetProjectJSON()))
```

You can then traverse that object for specific information. *Note that changing this object will not affect the project.* As far as I know you can only get information.

For example, to get a sprite by name:

```js
/* proj obj */.children.filter(function(sprite) {
  return sprite.objName === 'Sprite1'
})[0]
```

..and to get a variable's value:

```js
/* sprite obj */
  .variables.filter(function(variable) {
    return variable.name === 'asdf'
  })[0].value
```

**Comment by thisandagain** [comment]
That's correct. Thanks @liam4

**Comment by liam4** [comment]
Hmm.. ScratchX doesn't seem to implement `ASgetProjectJSON`..
